### ISSUE TITLE
Color preview, no range of color

### ISSUE THREAD

**Issue by Johnn5** [farbelous/bootstrap-colorpicker#205]
This might be an isolated issue, but the color picker doesnt seem to have range from solid to transparent etc

[screenshot](http://imgh.us/Capture_284.jpg)

**Comment by Fepaje** [comment]
Same problem here

**Comment by pascalbeynel** [comment]
Same problem !

**Comment by itsjavi** [comment]
Sorry but without more information and live examples reproducing the issue I can't help you.

It also declared explicitly that before opening an issue you should follow these steps: https://github.com/farbelous/bootstrap-colorpicker/blob/master/CONTRIBUTING.md#steps-to-submit-an-issue otherwise the issue will be closed.

<img width="814" alt="screen shot 2017-09-24 at 23 39 34" src="https://user-images.githubusercontent.com/122741/30787093-c59ab04c-a181-11e7-85b6-c9273579ce45.png">

Thanks for understanding

**Comment by pascalbeynel** [comment]
I find a solution : the problem come from the plugin integration. I use bower / gulp so i get a minified version of my CSS with all my libs. This one has reference to ../img/bootstrap-colorpicker directory which does not exists from my assets dir as these directory is in the vendor directory.
I have just copied the img dir from the vendor directory to my assets/img dir so path to images is not broken.

**Comment by itsjavi** [comment]
Bower support will be dropped soon.
Please use npm instead for this library.

**Comment by pascalbeynel** [comment]
Ok thanks
