### ISSUE TITLE
Colorpicker position changes when used inside a popup

### ISSUE THREAD

**Issue by Jaaichandran** [farbelous/bootstrap-colorpicker#210]
I have a requirement where user need to select colors for 10 items inside a popup. While using the color picker, when we click on the color picker of an item and scroll the page then the color palette shown for the item also moves with the scrolling and showed near another item. This cause issue in my app, like when user scrolls,  the palette is shown near another item instead of the selected one. Also the last item's color palette isn't even completely visible.

Anything can be done to keep the palette attached to the selection when the popup is scrolled ?

**Comment by Jaaichandran** [comment]
Anybody have comments on the above issue.

**Comment by itsjavi** [comment]
Sorry but without more information and **live examples** reproducing the issue I can't help you.

It also declared explicitly, when you are creating a new issue, that before opening it you should follow these steps: https://github.com/farbelous/bootstrap-colorpicker/blob/master/CONTRIBUTING.md#steps-to-submit-an-issue otherwise the issue will be closed.

<img width="814" alt="screen shot 2017-09-24 at 23 39 34" src="https://user-images.githubusercontent.com/122741/30787093-c59ab04c-a181-11e7-85b6-c9273579ce45.png">

Thanks for understanding
