### ISSUE TITLE
Support the left to right direction (RTL)

### ISSUE THREAD

**Issue by HakamFostok** [farbelous/bootstrap-colorpicker#218]
I am using bootstrap in a website, and website support more than languages (some of them are Right-To-Left). when changing the language of the site to the RTL then the color picker take very very large width.
any ideas to solve this.

**Comment by itsjavi** [comment]
Sorry but without more information and live examples reproducing the issue I can't help you.

It also declared explicitly, when you are creating a new issue, that before opening it you should follow these steps: https://github.com/farbelous/bootstrap-colorpicker/blob/master/CONTRIBUTING.md#steps-to-submit-an-issue otherwise the issue will be closed.

<img width="814" alt="screen shot 2017-09-24 at 23 39 34" src="https://user-images.githubusercontent.com/122741/30787093-c59ab04c-a181-11e7-85b6-c9273579ce45.png">

Thanks for understanding
