### ISSUE TITLE
Color picker position in modal

### ISSUE THREAD

**Issue by sguedon** [farbelous/bootstrap-colorpicker#219]
I've got an issue on color picker position in a modal.

Modal content is:
![image](https://user-images.githubusercontent.com/29616237/27453381-8a95156c-5796-11e7-90bd-56217dcaf7f1.png)

But when visible it appears at the bottom right expanding the modal:
![image](https://user-images.githubusercontent.com/29616237/27453417-ae364af4-5796-11e7-9523-8ea8817474a5.png)

if using:
('.colorselection').colorpicker({ container: true   });

or end of body if not

**Comment by itsjavi** [comment]
Sorry but without more information and live examples reproducing the issue I can't help you.

It also declared explicitly, when you are creating a new issue, that before opening it you should follow these steps: https://github.com/farbelous/bootstrap-colorpicker/blob/master/CONTRIBUTING.md#steps-to-submit-an-issue otherwise the issue will be closed.

<img width="814" alt="screen shot 2017-09-24 at 23 39 34" src="https://user-images.githubusercontent.com/122741/30787093-c59ab04c-a181-11e7-85b6-c9273579ce45.png">

This issue will be closed for now. Thanks for understanding
