### ISSUE TITLE
when parent element zoom changes, the plugin doesn't work properly

### ISSUE THREAD

**Issue by georgeorfanidi** [farbelous/bootstrap-colorpicker#249]
### Description

{Please write here}

### Context

- bootstrap-colorpicker version:  3
- bootstrap version: {Please write here}
- jQuery version: {Please write here}
- Browser name and version: Chrome
- Operative System name an version: {Please write here}

### Expected behavior

{Please write here}

### Actual behavior

{Please write here}

### Live Example

https://codepen.io/intzizou/pen/BYQKyR?editors=1011

**Comment by itsjavi** [comment]
Right, it may have something to do with the slider settings (size, position) and the position of the eye drop too, so that zoom should be applied to them too.

I tried with scale `document.body.style.transform = "scale(0.8)";` and it works a bit better.

**Comment by itsjavi** [comment]
I found out that it's almost impossible to detect parent element zoom without doing nasty/hacky stuff. I would recommend to not apply a zoom to parent elements that contain a color picker or any mouse/touch-movement related plugin.

As said, a general page zoom has any problem.

Closing this issue since there is no way to properly fix this, but following the recommendation I just said.
