### ISSUE TITLE
Do not update input field if user types in it

### ISSUE THREAD

**Issue by balazs-zsoldos** [farbelous/bootstrap-colorpicker#277]
### Description

{Please write here}

### Context

bootstrap-colorpicker version: 3.0.3

Options:
    {
        format: 'hex',
        autoInputFallback: false
    }

### Expected behavior

When I type a color, it should not update it at all. Input field should be updated only if I select a color with my mouse from the popup window.

### Actual behavior

If I start typing #AAA it is replaced with #AAAAAA. If I try to push backspace to correct it, it always writes back a character.

### Live Example

You can use your jsfiddle to check, replace the options with the above.

**Comment by andrewv86** [comment]
Yup, having the exact same issue, cannot type out specifically the desired color I want on any of the website examples.

**Comment by OneOfA11** [comment]
Nope, the workarounds does not work at all.

**Comment by balazs-zsoldos** [comment]
@OneOfA11 It works for me with latest stable. I am sorry to hear that it does not work for you.

**Comment by itsjavi** [comment]
hi @balazs-zsoldos, the purpose of `autoInputFallback` is to stop falling back to a fallback color in case the input contains an invalid one. Whenever a valid color is typed, then the plugin converts it to the proper format, that's why the input changes.

Maybe there could be another option to completely disable string substitution on input typing. That could be useful for other cases. What do you think?

(Btw it is nice to see that someone finds the extensions API useful)

**Comment by balazs-zsoldos** [comment]
@itsjavi Yes, "another option to completely disable string substitution on input typing" would be pretty useful. I think that is how 2.x works and the component is more usable if I use only the keyboard during filling the form.

**Comment by benjamindell** [comment]
This is an important feature for us as well

**Comment by rstueven** [comment]
@balazs-zsoldos Would you happen to have a straight JavaScript version of your workaround? Typescript isn't an option for my project.

**To whom it may concern:** Please fix this. It's annoying for the user to only be able to type three characters before having the colorpicker override whatever they had in mind. (E.g. "fed" gets changed to "FFEEDD")
